# Generated by Django 6.0.3 on 2026-04-04 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        ('recipes', '0004_recipecosthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('toplam_sepet', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Market Sepeti (TL)')),
                ('porsiyon_maliyeti', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif Maliyeti (TL)')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Hesaplanma Tarihi')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_costs', to='recipes.recipe', verbose_name='Tarif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_costs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
