# Generated by Django 6.0.3 on 2026-04-03 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Maliyet (TL)')),
                ('date_recorded', models.DateField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_history', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
    ]
